CREATE TABLE IF NOT EXISTS color (
    colorid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS polygon (
    polygonid BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    colorid BIGINT NOT NULL REFERENCES color(colorid) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS polygon_colorid_idx
    ON polygon(colorid);

CREATE TABLE IF NOT EXISTS vertexpolygon (
    polygonid BIGINT NOT NULL REFERENCES polygon(polygonid) ON DELETE CASCADE,
    vertexorder INTEGER NOT NULL CHECK (vertexorder > 0),
    x DOUBLE PRECISION NOT NULL,
    y DOUBLE PRECISION NOT NULL,
    PRIMARY KEY (polygonid, vertexorder)
);

CREATE INDEX IF NOT EXISTS vertexpolygon_polygonid_idx
    ON vertexpolygon(polygonid);
